### ISSUE TITLE
(node:8940) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'undefined'

### ISSUE THREAD

**Issue by Zerlingg** [xixi52/discord-canvas#11]
(node:8940) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'undefined'
    at setSource (C:\Users\Giingu\Desktop\Discord.Bot.Maker\BOTS\NezukoBot\node_modules\discord-canvas\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Giingu\Desktop\Discord.Bot.Maker\BOTS\NezukoBot\node_modules\discord-canvas\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Giingu\Desktop\Discord.Bot.Maker\BOTS\NezukoBot\node_modules\discord-canvas\node_modules\canvas\index.js:34:15
    at Object.loadImage (C:\Users\Giingu\Desktop\Discord.Bot.Maker\BOTS\NezukoBot\node_modules\discord-canvas\node_modules\canvas\index.js:23:10)
    at Welcome.toAttachment (C:\Users\Giingu\Desktop\Discord.Bot.Maker\BOTS\NezukoBot\node_modules\discord-canvas\src\greetings\Base.js:149:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async eval (eval at Actions.eval (C:\Users\Giingu\Desktop\Discord.Bot.Maker\BOTS\NezukoBot\bot.js:344:10), <anonymous>:6:14)
(node:8940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

Using:
Discord.js v12.2.0
discord-canvas v1.3.2

**Comment by hiro-akiba** [comment]
And the code you are using ._. ?

**Comment by hasib-rashid** [comment]
Please provide the code .___.
