### ISSUE TITLE
  return Canvas._registerFont(fs.realpathSync(src), fontFace)

### ISSUE THREAD

**Issue by yADGithub** [xixi52/discord-canvas#21]
return Canvas._registerFont(fs.realpathSync(src), fontFace)
                ^

Error: Could not parse font file
    at Object.registerFont (C:\Users\Home\Desktop\Secretaria\Discord\Programação\Bots\star\star-developer\node_modules\canvas\index.js:48:17)        
    at Object.<anonymous> (C:\Users\Home\Desktop\Secretaria\Discord\Programação\Bots\star\star-developer\node_modules\discord-canvas\index.js:3:8)   
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Home\Desktop\Secretaria\Discord\Programação\Bots\star\star-developer\src\commands\Others\fnshop.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\Users\Home\Desktop\Secretaria\Discord\Programação\Bots\star\star-developer\bot.js:100:21
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! star@1.0.0 start: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the star@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2021-01-07T15_18_05_141Z-debug.log

**Comment by Shadyyey** [comment]
code?????
-.-

**Comment by yADGithub** [comment]
no, it only gave this error when I downloaded the npm

**Comment by Shadyyey** [comment]
oh

**Comment by Shadyyey** [comment]
Well idk

**Comment by Shadyyey** [comment]
@yADGithub Try re-installing discord-canvas and canvas.

**Comment by Vozmak** [comment]
i have it problem too

**Comment by Yan-Jobs** [comment]
Ok send me your code pls

**Comment by Yan-Jobs** [comment]
@Vozmak

**Comment by Vozmak** [comment]
> Ok send me your code pls

Hi. The error appears immediately upon require
Const Canvas = require("discord-canvas")

**Comment by Yan-Jobs** [comment]
Try `npm uninstall discord-Canvas` then `npm i discord-canvas`

**Comment by Vozmak** [comment]
> Try `npm uninstall discord-Canvas` then `npm i discord-canvas`

Anyway @Yan-Jobs

**Comment by Vozmak** [comment]
Full error 

 return Canvas._registerFont(fs.realpathSync(src), fontFace)
                ^

Error: Could not parse font file
    at Object.registerFont (C:\Users\HP\Desktop\Текст и войс\node_modules\canvas\index.js:48:17)
    at Object.<anonymous> (C:\Users\HP\Desktop\Текст и войс\node_modules\discord-canvas\index.js:3:8)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\Текст и войс\commands\!profile.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\Users\HP\Desktop\Текст и войс\index.js:38:21

**Comment by Yan-Jobs** [comment]
2s

**Comment by Yan-Jobs** [comment]
Do u have this file ?

**Comment by Vozmak** [comment]
sec

**Comment by Vozmak** [comment]
in canvas or discord-canvas?

**Comment by Vozmak** [comment]
![image](https://user-images.githubusercontent.com/53349805/115051680-c1bcb000-9ee5-11eb-9559-c2e842370551.png)
Yes, have

**Comment by Yan-Jobs** [comment]
Is it empty ?

**Comment by Vozmak** [comment]
no

**Comment by Yan-Jobs** [comment]
Ah

**Comment by Vozmak** [comment]
font in my language in this file

**Comment by Vozmak** [comment]
sry for my english

**Comment by Yan-Jobs** [comment]
Try copy all your files in a new directory but don’t copy this files: package-lock.json or yarn.lock node_modules folder

**Comment by Yan-Jobs** [comment]
> sry for my english

I don’t care I am french 13 yrs old

**Comment by Yan-Jobs** [comment]
> Try copy all your files in a new directory but don’t copy this files: package-lock.json or yarn.lock node_modules folder

And reinstall dependency with `npm init -y` Or `yarn (I think)` and `npm install` or `yarn install`

**Comment by Vozmak** [comment]
ok, i try it later, thx

**Comment by Vozmak** [comment]
Anyway, i create absolutly new project and anyway error @Yan-Jobs

**Comment by Yan-Jobs** [comment]
Ah euh that’s not a good thing

**Comment by Vozmak** [comment]
yes( very good npm, but dont work, ah

**Comment by Yan-Jobs** [comment]
xD

**Comment by Yan-Jobs** [comment]
Tomorrow I will dm the creator and ask him your problem

**Comment by Vozmak** [comment]
Ok, thx

**Comment by Yan-Jobs** [comment]
DMed @Vozmak

**Comment by Vozmak** [comment]
> DMed @Vozmak 
> 
> 

Ok, I wait

**Comment by Yan-Jobs** [comment]
@xixi52 c’est là xD

**Comment by Yan-Jobs** [comment]
Enfin tu peux aussi voir les autres lmao

**Comment by OfficialRDB** [comment]
(process:12152): Pango-WARNING **: 18:08:16.010: couldn't load font "Keep Calm Medium Not-Rotated 37px", falling back to "Sans Medium Not-Rotated 37px", expect ugly output.

The fonts don't load. Even while they are in the right place. I even installed the fonts on my windows machine just in case.
