### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by LuisDavi-Tech** [xixi52/discord-canvas#31]
Error: Cannot find module 'moment'
Require stack:
- C:\Users\LuisDavi\Desktop\Projects\Discord-Police\node_modules\discord-canvas\src\fortnite\Shop.js
- C:\Users\LuisDavi\Desktop\Projects\Discord-Police\node_modules\discord-canvas\index.js
- C:\Users\LuisDavi\Desktop\Projects\Discord-Police\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Object.<anonymous> (C:\Users\LuisDavi\Desktop\Projects\Discord-Police\node_modules\discord-canvas\src\fortnite\Shop.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\LuisDavi\\Desktop\\Projects\\Discord-Police\\node_modules\\discord-canvas\\src\\fortnite\\Shop.js',
    'C:\\Users\\LuisDavi\\Desktop\\Projects\\Discord-Police\\node_modules\\discord-canvas\\index.js',
    'C:\\Users\\LuisDavi\\Desktop\\Projects\\Discord-Police\\index.js'
  ]
}

**Comment by TheYanilkatt** [comment]
Install it lmao 😆.
`npm i moment`

**Comment by Yan-Jobs** [comment]
@xixi52 tu peux fermer l’issue stp ?
