### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by RonaldZav** [xixi52/discord-canvas#63]
`Error: Unsupported image type`

```
const image = await new Canvas.Welcome()
  .setUsername(`${interaction.user.username}`)
  .setDiscriminator(`${interaction.user.discriminator}`)
  .setMemberCount(`${interaction.guild.memberCount}`)
  .setGuildName(`${interaction.guild.name}`)
  .setAvatar(`${user.displayAvatarURL({ dynamic: true, size: 256})}`)
  .setColor("border", "#ffffff")
  .setColor("username-box", "#6b6b6b")
  .setColor("discriminator-box", "#4d4d4d")
  .setColor("message-box", "#4d4d4d")
  .setColor("title", "#4d4d4d")
  .setColor("avatar", "#4d4d4d")
  .setBackground("./src/images/background.jpg")
  .toAttachment();
  ```
  
It gives an error with the avatar image, help.

**Comment by Androz2091** [comment]
displayAvatarURL returns a webp link

**Comment by Androz2091** [comment]
It should be a PNG. Just change the extension

**Comment by RonaldZav** [comment]
> It should be a PNG. Just change the extension

How do I change the extension to png?

**Comment by xixi52** [comment]
Use : `displayAvatarURL({ format: 'png' });`

**Comment by RonaldZav** [comment]
> Use : `displayAvatarURL({ format: 'png' });`

Code: `.setAvatar(member.user.displayAvatarURL({ format: 'png' }))`

```
Error: Unsupported image type
    at setSource (C:\Program Files\nodejs\SuperAddon\node_modules\canvas\lib\image.js:94:13)
    at C:\Program Files\nodejs\SuperAddon\node_modules\canvas\lib\image.js:62:11
    at C:\Program Files\nodejs\SuperAddon\node_modules\simple-get\index.js:97:7
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\SuperAddon\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) uncaughtException
    ```

**Comment by Sattishh** [comment]
+1

I'm getting the same error while using ``.setAvatar(member.user.displayAvatarURL({ format: 'png' }))``

**Comment by pioupia** [comment]
Good evening,
It works perfectly for me, so I think a few things need to be clarified:

1. Your `Node.js` version
2. The version of the package you have
3. Your `Discord.js` version.

And if possible, be shure than `member.user.displayAvatarURL({ format: 'png' })` is not null or undefined and its path is valid.

You should also check if it is not the path of the background that is wrong.

**Comment by Izocel** [comment]
Same thing here:

```json
{
  "keywords": [],
  "main": "index.js",
  "name": "whatthechuckbot",
  "version": "1.0.0",
  "description": "A discord bot for welcoming cards",
  "author": "RVÐ",
  "license": "ISC",
  "scripts": {
    "build": "tsc",
    "start": "npm install && npm run build && node ./dist/index.js",
    "start:dev": "ts-node-dev ./src/index.ts",
    "start:prod": "node ./dist/index.js",
    "start:min": "node ./distMin/index.js",
    "uglify": "node ./gulp/main.js",
    "watch": "tsc -w"
  },
  "dependencies": {
    "discord-canvas": "^1.5.2",
    "discord.js": "^14.11.0",
    "dotenv": "^16.3.1",
    "glob": "^10.3.3",
    "node-fetch": "^3.3.1",
    "pino": "^8.14.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.8",
    "@types/glob": "^8.1.0",
    "@types/jquery": "^3.5.16",
    "@types/node": "^20.4.1",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-uglify": "^3.0.2",
    "ts-node": "^10.9.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.1.6",
    "uglify-js": "^3.17.4"
  }
}
```

```ts
import internal from "stream";
import { theme } from "../..";
import { ALLOWED_EXTENSIONS, AttachmentBuilder, BufferResolvable, GuildMember, TextBasedChannel } from "discord.js";
const Canvas = require("discord-canvas");

export class CardHelper {

    public attachment: BufferResolvable | internal.Stream

    send(channel: TextBasedChannel) {
        channel.sendTyping()
        channel.send({
            files: [this.attachment]
        })
    }

    async render(member: GuildMember) {
        const welcomeCard = new Canvas.Welcome();
        welcomeCard.setUsername(member.displayName)
        .setAvatar(member.user.displayAvatarURL({ forceStatic: true, extension: ALLOWED_EXTENSIONS[0]}))
            .setGuildName(member.guild.name)
            .setMemberCount(member.guild.memberCount);

        welcomeCard.textTitle = "Welcome";
        welcomeCard.textMessage = `Welcome to ${member.guild.name}`;
        theme.setRndWelcomeStyle(welcomeCard);

        const image = await welcomeCard.toAttachment();
        this.attachment = new AttachmentBuilder(image.toBuffer()).attachment;
        return this;
    }
}

```
